name: Pipeline del examen
on:
  workflow_dispatch:
  push:
jobs:
  Build:
    runs-on: ubuntu-latest
    env:
      GITHUB_LOGIN: ${{ github.actor }}
      GITHUB_PACKAGES: ${{ secrets.GITHUB_TOKEN }}
      GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Clonando el repositorio y estableciendo el espacio de trabajo
        uses: actions/checkout@v3
      - name: Configurando java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Construyendo y probando el código
        run: |
          chmod +x gradlew        
          ./gradlew assemble
  Test:
    runs-on: ubuntu-latest
    needs: Build
    steps:
      - name: Clonando el repositorio y estableciendo el espacio de trabajo
        uses: actions/checkout@v3
      - name: Configurando java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Ejecutando los test
        run: |
          chmod +x gradlew        
          ./gradlew test
  Mail:
    runs-on: ubuntu-latest
    needs: Test
    steps:
        - name: Enviar correo
          uses: dawidd6/action-send-mail@v3.7.2
          with:
            server_address: smtp.gmail.com
            server_port: 587
            username: ${{ secrets.EMAIL }}
            password: ${{ secrets.PASSWORD }}
            subject: "Resultado de la ejecución de los tests"
            body: "Los tests se han ejecutado correctamente"
            to: ${{ secrets.EMAIL_TO }}
            from: criramnav1